import { mkdir } from "node:fs/promises";
import { chromium } from "playwright";
const OUT = "shots/demo";
const b = await chromium.launch({ args:["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader","--ignore-gpu-blocklist"] });
const p = await b.newPage({ viewport:{width:1600,height:1000}, deviceScaleFactor:2 });
const errs=[]; p.on("pageerror",e=>errs.push(String(e).slice(0,160)));
p.on("response",r=>{ if(r.status()>=400) errs.push(`${r.status()} ${r.url().slice(-50)}`); });
await mkdir(OUT,{recursive:true});
await p.goto("http://127.0.0.1:5173/demo",{waitUntil:"domcontentloaded"});
await p.waitForTimeout(1200);
await p.screenshot({path:`${OUT}/1-ingest.png`});
console.log("ingest shot");
await p.waitForFunction(()=>!document.querySelector(".ingest"),{timeout:90000});
await p.waitForTimeout(2500);
await p.screenshot({path:`${OUT}/2-inspect.png`});
console.log("meshes loaded, inspect shot");
await p.getByRole("button",{name:/Trace/}).click(); await p.waitForTimeout(2200);
await p.screenshot({path:`${OUT}/3-trace.png`});
await p.getByRole("button",{name:/Improve/}).click(); await p.waitForTimeout(900);
await p.screenshot({path:`${OUT}/4-improve.png`});
await p.getByRole("button",{name:/Accept and apply/}).first().click(); await p.waitForTimeout(1600);
await p.screenshot({path:`${OUT}/5-accepted.png`});
await p.getByRole("button",{name:/^\d?\s*Fly/}).click().catch(()=>p.getByRole("button",{name:/Fly/}).click());
await p.waitForTimeout(5000);
await p.screenshot({path:`${OUT}/6-fly.png`});
await p.waitForTimeout(4000);
await p.screenshot({path:`${OUT}/7-fly-later.png`});
console.log("errors:",errs.length); errs.slice(0,6).forEach(e=>console.log("  ",e));
await b.close();
