import { mkdir } from "node:fs/promises";
import { chromium } from "playwright";
const b = await chromium.launch({args:["--use-gl=angle","--use-angle=swiftshader","--enable-unsafe-swiftshader","--ignore-gpu-blocklist"]});
const p = await b.newPage({viewport:{width:1600,height:1000},deviceScaleFactor:2});
const e=[];p.on("pageerror",x=>e.push(String(x).slice(0,140)));
p.on("response",r=>{if(r.status()>=400)e.push(`${r.status()} ${r.url().slice(-40)}`)});
await mkdir("shots/wb",{recursive:true});
await p.goto("http://127.0.0.1:5173/",{waitUntil:"domcontentloaded"});
await p.waitForTimeout(1500);
await p.getByRole("button",{name:/Import a design/i}).click();
await p.waitForSelector(".schematic-canvas canvas",{timeout:60000});
await p.waitForTimeout(6000);
await p.screenshot({path:"shots/wb/1-inspect.png"});
await p.getByRole("button",{name:/Colour by risk/i}).click(); await p.waitForTimeout(1200);
await p.screenshot({path:"shots/wb/2-risk.png"});
const c=p.getByRole("button",{name:/Confirm units, frame/i});
if(await c.count()){await c.click();await p.waitForTimeout(3500);}
await p.getByRole("button",{name:"Improve",exact:true}).click();
await p.getByRole("button",{name:/Generate proposals/i}).click();
await p.waitForTimeout(7000);
await p.screenshot({path:"shots/wb/3-proposals.png"});
console.log("proposal cards:",await p.locator(".card.is-proposal").count());
await p.getByRole("button",{name:"Simulate",exact:true}).click();
await p.waitForTimeout(4000);
await p.screenshot({path:"shots/wb/4-fly.png"});
await p.waitForTimeout(3000);
await p.screenshot({path:"shots/wb/5-fly2.png"});
console.log("errors:",e.length);e.slice(0,5).forEach(x=>console.log("  ",x));
await b.close();
