"""Deterministic candidate generation (architecture section 7, step 2).

"Generate bounded candidates from failing checks and typed dependency paths." Everything here is
arithmetic and graph traversal; no model is consulted. Section 4 is explicit that this path must
produce useful proposals with no API access, so the provider adapter is an addition to this, never
a replacement for it.

Each generator answers one failing or unknown check and states the evidence it used. A generator
that cannot establish its preconditions produces nothing rather than a guess - notably, the removal
family from the tentative specification is absent entirely, because section 3 rules that missing
redundancy, manufacturing, or load-path knowledge prevents removal recommendations.
"""

from __future__ import annotations

import math
from dataclasses import dataclass

from dronebench_contracts import (
    CatalogSnapshot,
    Claim,
    DeclaredInterface,
    Evaluation,
    EvidenceRequest,
    GeometryFeatures,
    MAX_CANDIDATES,
    Mission,
    PartOccurrence,
    PartsDocument,
    ReplaceCatalogComponent,
    ResizeSpar,
    SetWingTipExtension,
    TranslateComponent,
)
from dronebench_graph import evidence_path_to_constraint
from dronebench_contracts.graph import ExplanationPath


@dataclass(frozen=True)
class Candidate:
    """A proposal before it has been previewed."""

    key: str
    title: str
    issue: str
    operation: object
    rationale: str
    prerequisites: tuple[str, ...]
    evidence_ids: tuple[str, ...]
    answers_check_id: str | None
    evidence_path: ExplanationPath | None = None


def generate(
    *,
    parts: PartsDocument,
    features: GeometryFeatures,
    mission: Mission,
    evaluation: Evaluation,
    catalog: CatalogSnapshot,
    graph=None,
) -> tuple[list[Candidate], list[EvidenceRequest]]:
    """Return ``(candidates, evidence_requests)`` within the section 7 budget.

    Evidence requests come first in priority: an edit ranked on unknown inputs is theatre, so when
    a required check is unknown the missing fact is surfaced before any proposal that claims a gain.
    """
    requests = _evidence_requests(parts=parts, evaluation=evaluation)

    candidates: list[Candidate] = []
    candidates += _cg_candidates(parts=parts, mission=mission, evaluation=evaluation, graph=graph)
    candidates += _spar_candidates(
        parts=parts, features=features, mission=mission, evaluation=evaluation, catalog=catalog,
        graph=graph,
    )
    candidates += _energy_candidates(
        parts=parts, mission=mission, evaluation=evaluation, catalog=catalog, graph=graph
    )
    candidates += _mass_candidates(
        parts=parts, mission=mission, evaluation=evaluation, catalog=catalog, graph=graph
    )
    candidates += _span_candidates(
        parts=parts, features=features, mission=mission, evaluation=evaluation, graph=graph
    )

    # Deduplicate by the part and operation they touch; keep the earliest, which is the one
    # generated by the more urgent check.
    seen: set[tuple[str, str]] = set()
    unique: list[Candidate] = []
    for candidate in candidates:
        signature = (candidate.operation.operation, candidate.operation.target_part_id)
        if signature in seen:
            continue
        seen.add(signature)
        unique.append(candidate)

    return unique[:MAX_CANDIDATES], requests


# ---------------------------------------------------------------------------------------------
# Missing evidence
# ---------------------------------------------------------------------------------------------


def _evidence_requests(
    *, parts: PartsDocument, evaluation: Evaluation
) -> list[EvidenceRequest]:
    """One request per occurrence whose unknown mass is blocking a required check."""
    blocked = [c.check_id for c in evaluation.required_unknown()]
    if not blocked:
        return []

    requests: list[EvidenceRequest] = []
    for occurrence in parts.occurrences:
        if occurrence.mass_kg.is_known:
            continue
        requests.append(
            EvidenceRequest(
                request_id=f"req_{occurrence.part_id.replace('prt_', '')}-mass",
                base_revision_id=parts.revision_id,
                title=f"Supply a measured mass for {occurrence.name}",
                quantity=f"{occurrence.part_id}.mass_kg",
                unit="kg",
                target_part_id=occurrence.part_id,
                why_it_matters=(
                    f"{occurrence.name} has no mass evidence, so all-up mass and centre of gravity "
                    "cannot be computed, and every weight-dependent result stays unknown. A filled "
                    "bounding envelope is not a substitute: geometry does not determine mass."
                ),
                blocked_check_ids=blocked,
                suggested_source_kinds=["bom", "manual"],
            )
        )
    return requests


# ---------------------------------------------------------------------------------------------
# Centre of gravity
# ---------------------------------------------------------------------------------------------


def _cg_candidates(*, parts, mission: Mission, evaluation: Evaluation, graph) -> list[Candidate]:
    """Move a movable mass along its corridor to bring the CG inside the envelope.

    Only mount positions that are actually available are proposed, and the move must land the CG
    inside the envelope by calculation before it is offered. Section 7 step 5 still previews it for
    real; this is a screen, not a promise.
    """
    check = _check(evaluation, "cg_envelope")
    if check is None or check.status not in ("fail",):
        return []

    total_mass, moment_x = _mass_and_moment(parts)
    if total_mass is None or moment_x is None:
        return []

    lo, hi = mission.cg_envelope_station_m
    target_station = (lo + hi) / 2
    out: list[Candidate] = []

    for occurrence in parts.occurrences:
        if "translate_component" not in occurrence.edit_capabilities:
            continue
        if occurrence.locked or occurrence.part_id in mission.locked_part_ids:
            continue
        corridor = occurrence.travel_corridor
        mass = occurrence.mass_kg.number()
        if corridor is None or mass is None or corridor.axis != "x":
            continue

        current_x = occurrence.transform.translation[0]
        # Moving this mass by d changes x_CG by mass*d/total. Solve for the d that centres the CG.
        wanted_delta = (-target_station - (moment_x / total_mass)) * total_mass / mass

        options = corridor.mount_positions_m or [corridor.min_m, corridor.max_m]
        feasible = []
        for position in options:
            delta = position - current_x
            if delta == 0.0 or not corridor.contains(position):
                continue
            station = -((moment_x + mass * delta) / total_mass)
            if lo <= station <= hi:
                feasible.append((abs(delta), delta, position, station))
        if not feasible:
            continue

        # Smallest move that works: section 10 wants the minimum intelligible change, and a short
        # travel keeps the harness allowance comfortable.
        _, delta, position, station = min(feasible)

        path = (
            evidence_path_to_constraint(graph, occurrence.part_id, "cg_envelope")
            if graph is not None
            else None
        )
        out.append(
            Candidate(
                key=f"{occurrence.part_id}-cg",
                title=f"Move {occurrence.name} forward {abs(delta) * 1000:.0f} mm",
                issue=(
                    f"Centre of gravity is at station {-(moment_x / total_mass):.3f} m, outside the "
                    f"{lo:.3f}-{hi:.3f} m envelope."
                ),
                operation=TranslateComponent(
                    target_part_id=occurrence.part_id,
                    axis="x",
                    delta_m=round(delta, 6),
                ),
                rationale=(
                    f"Relocating {mass:.3f} kg by {delta * 1000:+.0f} mm along the declared "
                    f"corridor moves the centre of gravity to station {station:.3f} m, inside the "
                    f"envelope. The mount position {position:+.3f} m is one of the corridor's "
                    "declared positions and the harness allowance covers the travel. Geometry "
                    "shapes are unchanged - this is a placement change, so fixed-geometry "
                    "aerodynamic coefficients may be reused."
                ),
                prerequisites=(
                    "travel corridor declared",
                    "harness allowance known",
                    "mount positions known",
                    f"{occurrence.part_id} mass established from BOM evidence",
                ),
                evidence_ids=tuple(occurrence.mass_kg.evidence_ids),
                answers_check_id="cg_envelope",
                evidence_path=path,
            )
        )
    return out


# ---------------------------------------------------------------------------------------------
# Spar
# ---------------------------------------------------------------------------------------------


def _spar_candidates(
    *, parts, features, mission: Mission, evaluation: Evaluation, catalog: CatalogSnapshot, graph
) -> list[Candidate]:
    """Offer the next compatible tube up.

    Generated when the stress check fails, and also when it passes with headroom in the mass
    budget - section 14 wants a spar proposal whose tradeoff (more margin, more mass) is visible
    enough to decline. Either way the mass cost is stated in the rationale, never hidden.
    """
    check = _check(evaluation, "spar_stress")
    if check is None or check.status == "not_applicable":
        return []

    spars = [o for o in parts.occurrences if "resize_spar" in o.edit_capabilities]
    if not spars:
        return []
    spar = spars[0]

    definition = parts.definition(spar.definition_id)
    current_outer = definition.parameters.get("outer_diameter_m")
    current_inner = definition.parameters.get("inner_diameter_m")
    length = definition.parameters.get("length_m")
    if current_outer is None or current_inner is None or length is None:
        return []

    density = definition.claims.number("density_kgm3")
    allowable = definition.claims.number("allowable_stress_pa")
    if density is None or allowable is None:
        # Section 6: the material assumption must be declared before a resize is proposable.
        return []

    current_mass = _tube_mass(current_outer, current_inner, length, density)
    total_mass, _ = _mass_and_moment(parts)

    upgrades = []
    for item in catalog.of_category("spar"):
        outer = item.claims.get("outer_diameter_m")
        inner = item.claims.get("inner_diameter_m")
        if outer is None or inner is None:
            continue
        outer_v, inner_v = outer.number(), inner.number()
        if outer_v is None or inner_v is None or outer_v <= current_outer:
            continue
        upgrades.append((outer_v, inner_v, item))
    if not upgrades:
        return []

    outer_v, inner_v, item = min(upgrades)
    new_mass = _tube_mass(outer_v, inner_v, length, density)
    delta_mass = new_mass - current_mass

    if total_mass is not None:
        headroom = mission.max_takeoff_mass_kg - total_mass
        if delta_mass > headroom:
            # Proposing an edit that would immediately break the mass budget is not a proposal.
            return []

    current_i = _second_moment(current_outer, current_inner)
    new_i = _second_moment(outer_v, inner_v)
    margin_ratio = (new_i / current_i) * (current_outer / outer_v)

    failing = check.status == "fail"
    path = (
        evidence_path_to_constraint(graph, spar.part_id, "spar_stress")
        if graph is not None
        else None
    )
    return [
        Candidate(
            key=f"{spar.part_id}-resize",
            title=(
                f"Increase the spar to {outer_v * 1000:.0f} x {inner_v * 1000:.0f} mm"
            ),
            issue=(
                check.reason
                if failing
                else (
                    "Root bending stress is within allowable, but the structural margin can be "
                    "raised at a stated mass cost."
                )
            ),
            operation=ResizeSpar(
                target_part_id=spar.part_id,
                outer_diameter_m=outer_v,
                inner_diameter_m=inner_v,
                regenerate_mount_part_ids=[
                    o.part_id
                    for o in parts.occurrences
                    if o.role == "mount" and spar.part_id in o.allowed_contact_part_ids
                ],
            ),
            rationale=(
                f"The section modulus rises by a factor of {margin_ratio:.2f}, lowering root "
                f"bending stress by the same factor. It costs {delta_mass * 1000:+.0f} g, which "
                "shifts the mass budget and the centre of gravity, and the two compatible mounts "
                "are regenerated inside the same transaction. Bending stress alone omits buckling, "
                "joints, adhesive, and local damage; this proposal does not claim those are "
                "addressed."
            ),
            prerequisites=(
                "reconstructed tubular spar",
                "material density and allowable stress declared",
                "compatible mount bore regenerated in the same transaction",
            ),
            evidence_ids=tuple(item.evidence_ids) + tuple(
                definition.claims.get("allowable_stress_pa").evidence_ids  # type: ignore[union-attr]
            ),
            answers_check_id="spar_stress" if failing else None,
            evidence_path=path,
        )
    ]


# ---------------------------------------------------------------------------------------------
# Energy and mass
# ---------------------------------------------------------------------------------------------


def _energy_candidates(
    *, parts, mission: Mission, evaluation: Evaluation, catalog: CatalogSnapshot, graph
) -> list[Candidate]:
    """Swap to a higher-capacity pack that actually fits the bay and the electrical model."""
    check = _check(evaluation, "energy_reserve")
    if check is None or check.status != "fail":
        return []
    return _battery_swap(
        parts=parts,
        mission=mission,
        catalog=catalog,
        graph=graph,
        prefer="capacity",
        issue=check.reason,
        answers="energy_reserve",
    )


def _mass_candidates(
    *, parts, mission: Mission, evaluation: Evaluation, catalog: CatalogSnapshot, graph
) -> list[Candidate]:
    """Swap to a lighter pack when the mass budget is the binding constraint."""
    check = _check(evaluation, "mass_budget")
    if check is None or check.status != "fail":
        return []
    return _battery_swap(
        parts=parts,
        mission=mission,
        catalog=catalog,
        graph=graph,
        prefer="mass",
        issue=check.reason,
        answers="mass_budget",
    )


def _battery_swap(
    *, parts, mission: Mission, catalog: CatalogSnapshot, graph, prefer: str, issue: str, answers: str
) -> list[Candidate]:
    batteries = [
        o
        for o in parts.occurrences
        if o.role == "battery" and "replace_catalog_component" in o.edit_capabilities
    ]
    if not batteries:
        return []
    battery = batteries[0]
    current_mass = battery.mass_kg.number()
    bay = _bay_interface(parts, battery)

    fitting = []
    for item in catalog.of_category("battery"):
        envelope = item.interface_of("mass_envelope")
        if envelope is None:
            continue
        fits, _ = bay.fits(envelope)
        if not fits:
            continue
        electrical = item.interface_of("electrical_dc")
        if electrical is None or electrical.voltage_v is None:
            continue
        # The existing ESC and motor were selected for the current pack voltage. A different
        # voltage class is a different electrical model, which this operation does not cover.
        current_electrical = _current_pack_voltage(catalog, parts, battery)
        if current_electrical is not None and not _voltage_compatible(
            electrical.voltage_v, current_electrical
        ):
            continue
        capacity = item.claims.get("capacity_wh")
        mass = item.mass_kg.number()
        if capacity is None or mass is None:
            continue
        capacity_v = capacity.number()
        if capacity_v is None:
            continue
        fitting.append((capacity_v, mass, item))

    if not fitting:
        return []

    if prefer == "capacity":
        capacity_v, mass, item = max(fitting, key=lambda row: row[0])
    else:
        capacity_v, mass, item = min(fitting, key=lambda row: row[1])

    if current_mass is not None and abs(mass - current_mass) < 1e-9:
        return []

    return [
        Candidate(
            key=f"{battery.part_id}-swap-{item.catalog_item_id}",
            title=f"Replace the pack with {item.display_name}",
            issue=issue,
            operation=ReplaceCatalogComponent(
                target_part_id=battery.part_id, catalog_item_id=item.catalog_item_id
            ),
            rationale=(
                f"{item.display_name} carries {capacity_v:.1f} Wh at {mass:.3f} kg and fits the "
                "declared bay envelope and the existing pack voltage class. The BOM entry and the "
                "envelope are replaced atomically; unresolved fit or current checks block the "
                "commit rather than warning. This is a synthetic catalog entry with no implied "
                "real supplier offer."
            ),
            prerequisites=(
                "bay envelope declared",
                "pack voltage class matches the installed ESC",
                "mass and capacity present in the catalog snapshot",
            ),
            evidence_ids=tuple(item.evidence_ids),
            answers_check_id=answers,
            evidence_path=(
                evidence_path_to_constraint(graph, battery.part_id, answers)
                if graph is not None
                else None
            ),
        )
    ]


def _span_candidates(
    *, parts, features: GeometryFeatures, mission: Mission, evaluation: Evaluation, graph
) -> list[Candidate]:
    """A bounded tip extension, only when the endurance objective is the thing being pushed.

    This is the stretch operation of section 6 and the only one that invalidates the aerodynamic
    geometry, so it is offered last and only when the airframe has mass headroom for it.
    """
    check = _check(evaluation, "energy_reserve")
    if check is None or check.status != "fail":
        return []

    tips = [o for o in parts.occurrences if "set_wing_tip_extension" in o.edit_capabilities]
    if len(tips) < 2:
        return []
    left = next((o for o in tips if o.mirror_of is None), None)
    right = next((o for o in tips if o.mirror_of == (left.part_id if left else None)), None)
    if left is None or right is None:
        return []

    span = features.wing_span_m.number()
    if span is None:
        return []
    extension = 0.05  # 50 mm per side: bounded, and within the joint model of the fixture

    return [
        Candidate(
            key=f"{left.part_id}-tip",
            title=f"Extend each wing tip by {extension * 1000:.0f} mm",
            issue=check.reason,
            operation=SetWingTipExtension(
                target_part_id=left.part_id, extension_m=extension, paired_part_id=right.part_id
            ),
            rationale=(
                f"Span rises from {span:.2f} m to {span + 2 * extension:.2f} m, raising aspect "
                "ratio and lowering induced drag at the locked cruise condition. This changes the "
                "outer mold line, so the aerodynamic geometry is invalidated and both baseline and "
                "candidate must be re-solved at the same fidelity before any gain is shown."
            ),
            prerequisites=(
                "parameterised symmetric tip",
                "bounded span and a joint model",
                "both occurrences regenerated in one transaction",
            ),
            evidence_ids=tuple(features.wing_span_m.evidence_ids),
            answers_check_id="energy_reserve",
            evidence_path=(
                evidence_path_to_constraint(graph, left.part_id, "energy_reserve")
                if graph is not None
                else None
            ),
        )
    ]


# ---------------------------------------------------------------------------------------------
# Shared arithmetic
# ---------------------------------------------------------------------------------------------


def _check(evaluation: Evaluation, check_id: str):
    try:
        return evaluation.check(check_id)
    except KeyError:
        return None


def _mass_and_moment(parts: PartsDocument) -> tuple[float | None, float | None]:
    """``(total mass, sum of m*x)``. Returns ``(None, None)`` if any mass is unknown.

    Section 8: massless or missing-mass geometry does not quietly disappear.
    """
    total = 0.0
    moment = 0.0
    for occurrence in parts.occurrences:
        mass = occurrence.mass_kg.number()
        if mass is None:
            return None, None
        com = occurrence.world_com_m()
        if com is None:
            return None, None
        total += mass
        moment += mass * com[0]
    return (total, moment) if total > 0 else (None, None)


def _tube_mass(outer: float, inner: float, length: float, density: float) -> float:
    return math.pi * (outer**2 - inner**2) / 4.0 * length * density


def _second_moment(outer: float, inner: float) -> float:
    """``I = pi (Do^4 - Di^4) / 64`` for a tube."""
    return math.pi * (outer**4 - inner**4) / 64.0


def _bay_interface(parts: PartsDocument, battery: PartOccurrence) -> DeclaredInterface:
    """The envelope a replacement pack must fit inside, taken from the installed part's bounds."""
    bounds = battery.bounds_local_m
    if bounds is None:
        return DeclaredInterface(
            interface_id="if_bay_unknown", kind="mass_envelope", dimensions_m={}
        )
    length, width, height = bounds.size_m
    # A small allowance for the bay around the installed pack, from the declared harness allowance.
    slack = 0.005
    return DeclaredInterface(
        interface_id="if_bay_battery",
        kind="mass_envelope",
        dimensions_m={
            "length_max": length + slack,
            "width_max": width + slack,
            "height_max": height + slack,
        },
    )


def _current_pack_voltage(
    catalog: CatalogSnapshot, parts: PartsDocument, battery: PartOccurrence
) -> tuple[float, float] | None:
    """Voltage window of the pack currently installed, matched by mass and envelope."""
    installed_mass = battery.mass_kg.number()
    if installed_mass is None:
        return None
    for item in catalog.of_category("battery"):
        item_mass = item.mass_kg.number()
        if item_mass is None or abs(item_mass - installed_mass) > 1e-6:
            continue
        electrical = item.interface_of("electrical_dc")
        if electrical and electrical.voltage_v:
            return electrical.voltage_v
    return None


def _voltage_compatible(
    candidate: tuple[float, float], installed: tuple[float, float]
) -> bool:
    """Same voltage class: the windows must overlap substantially, not merely touch."""
    lo = max(candidate[0], installed[0])
    hi = min(candidate[1], installed[1])
    if hi <= lo:
        return False
    installed_width = installed[1] - installed[0]
    return (hi - lo) >= 0.5 * installed_width
